# Generated by Django 6.0.4 on 2026-05-20 03:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0005_lodginghost_latitude_lodginghost_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('default_weekday', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana en que normalmente se realiza', null=True, verbose_name='Día habitual')),
                ('default_start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('default_end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('color', models.CharField(default='#0B7FB3', help_text='Color para el calendario (hex)', max_length=7, verbose_name='Color')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'db_table': 'services_type',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('title', models.CharField(blank=True, help_text='Si es diferente al nombre del tipo', max_length=200, verbose_name='Título especial')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='services.servicetype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Servicio Programado',
                'verbose_name_plural': 'Servicios Programados',
                'db_table': 'services_schedule',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la parte')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Duración (min)')),
                ('max_participants', models.PositiveIntegerField(default=1, help_text='Cuántas personas pueden asignarse a esta parte', verbose_name='Máx. participantes')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='services.servicetype', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Parte del Servicio',
                'verbose_name_plural': 'Partes del Servicio',
                'db_table': 'services_part',
                'ordering': ['service_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EligibleMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_eligibilities', to='business.member', verbose_name='Miembro')),
                ('service_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_members', to='services.servicepart', verbose_name='Parte')),
            ],
            options={
                'verbose_name': 'Miembro Elegible',
                'verbose_name_plural': 'Miembros Elegibles',
                'db_table': 'services_eligible_member',
                'unique_together': {('member', 'service_part')},
            },
        ),
        migrations.CreateModel(
            name='ServiceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('leader', 'Líder / Principal'), ('participant', 'Participante'), ('support', 'Apoyo')], default='participant', max_length=20, verbose_name='Rol')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='business.member', verbose_name='Miembro')),
                ('service_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='services.servicepart', verbose_name='Parte')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='services.serviceschedule', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'services_assignment',
                'ordering': ['service_part__order', 'role'],
                'unique_together': {('schedule', 'service_part', 'member')},
            },
        ),
        migrations.AddIndex(
            model_name='serviceschedule',
            index=models.Index(fields=['date'], name='services_sc_date_7bb70e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceschedule',
            index=models.Index(fields=['service_type', 'date'], name='services_sc_service_2b3d96_idx'),
        ),
    ]
