# Generated by Django 6.0.4 on 2026-05-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='default_weekday',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='default_weekdays',
            field=models.CharField(blank=True, help_text='Días de la semana separados por coma (0=Lun, 1=Mar, 2=Mié, 3=Jue, 4=Vie, 5=Sáb, 6=Dom)', max_length=20, verbose_name='Días habituales'),
        ),
    ]
