# Generated by Django 6.0.4 on 2026-05-20 03:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_servicetype_default_weekday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], unique=True, verbose_name='Mes')),
                ('header_color', models.CharField(default='#1a3a5c', max_length=7, verbose_name='Color del encabezado')),
                ('accent_color', models.CharField(default='#1a3a5c', max_length=7, verbose_name='Color de acento')),
            ],
            options={
                'verbose_name': 'Color de Mes',
                'verbose_name_plural': 'Colores de Mes',
                'db_table': 'services_month_color',
                'ordering': ['month'],
            },
        ),
        migrations.AddField(
            model_name='servicetype',
            name='text_color',
            field=models.CharField(default='#000000', help_text='Color del texto en el reporte impreso (hex)', max_length=7, verbose_name='Color de texto'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='color',
            field=models.CharField(default='#0B7FB3', help_text='Color para el calendario (hex)', max_length=7, verbose_name='Color de fondo'),
        ),
    ]
