# Generated by Django 6.0.4 on 2026-04-18 00:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_member_baptism_date_member_baptism_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('period', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('annual', 'Anual')], default='annual', max_length=20, verbose_name='Período')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(verbose_name='Fecha fin')),
                ('total_income_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto de ingresos')),
                ('total_expense_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto de egresos')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'finance_budget',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('account_type', models.CharField(choices=[('cash', 'Efectivo / Caja'), ('checking', 'Cuenta Corriente'), ('savings', 'Cuenta de Ahorro'), ('investment', 'Inversión')], max_length=20, verbose_name='Tipo')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Número de cuenta')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo inicial')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo actual')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta Financiera',
                'verbose_name_plural': 'Cuentas Financieras',
                'db_table': 'finance_account',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('tithe', 'Diezmo'), ('offering', 'Ofrenda'), ('special_offering', 'Ofrenda Especial'), ('donation', 'Donación'), ('event_revenue', 'Ingreso de Evento'), ('other_income', 'Otros Ingresos'), ('utilities', 'Servicios (Luz, Agua, Internet)'), ('rent', 'Renta / Hipoteca'), ('salaries', 'Salarios / Honorarios'), ('ministry', 'Gastos de Ministerio'), ('maintenance', 'Mantenimiento'), ('supplies', 'Materiales y Suministros'), ('travel', 'Viajes y Transporte'), ('marketing', 'Publicidad / Marketing'), ('missions', 'Misiones'), ('other_expense', 'Otros Egresos')], max_length=30, verbose_name='Categoría')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('bank_transfer', 'Transferencia Bancaria'), ('check', 'Cheque'), ('digital', 'Pago Digital'), ('card', 'Tarjeta')], default='cash', max_length=20, verbose_name='Método de pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='completed', max_length=20, verbose_name='Estado')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Número de referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financialaccount', verbose_name='Cuenta')),
                ('related_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='business.member', verbose_name='Miembro relacionado')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'finance_transaction',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contribution_type', models.CharField(choices=[('tithe', 'Diezmo'), ('offering', 'Ofrenda'), ('special_offering', 'Ofrenda Especial'), ('pledge', 'Compromiso / Voto')], max_length=20, verbose_name='Tipo de contribución')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('one_time', 'Única vez')], default='one_time', max_length=20, verbose_name='Frecuencia')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('bank_transfer', 'Transferencia Bancaria'), ('check', 'Cheque'), ('digital', 'Pago Digital'), ('card', 'Tarjeta')], default='cash', max_length=20, verbose_name='Método de pago')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Número de recibo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='business.member', verbose_name='Miembro')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution', to='finance.transaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Contribución',
                'verbose_name_plural': 'Contribuciones',
                'db_table': 'finance_contribution',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'date'], name='finance_tra_transac_a36dff_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='finance_tra_categor_afb10f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='finance_tra_status_0941b9_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['member', 'date'], name='finance_con_member__b49b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['contribution_type'], name='finance_con_contrib_439f7e_idx'),
        ),
    ]
