# Generated by Django 6.0.4 on 2026-04-12 18:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_free_entry', models.BooleanField(default=True)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('service', 'Servicio'), ('conference', 'Conferencia'), ('retreat', 'Retiro'), ('workshop', 'Taller'), ('social', 'Social'), ('outreach', 'Alcance'), ('other', 'Otro')], default='service', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('ongoing', 'En Curso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'business_event',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('target_budget', models.DecimalField(decimal_places=2, default=0, help_text='Meta de recaudación', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='business.event')),
            ],
            options={
                'verbose_name': 'Event Budget',
                'verbose_name_plural': 'Event Budgets',
                'db_table': 'business_eventbudget',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('visitor', 'Visitante'), ('transferred', 'Transferido')], default='active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'business_member',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['status'], name='business_me_status_5f8756_idx'), models.Index(fields=['last_name', 'first_name'], name='business_me_last_na_177ac3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_contact_for_families', to='business.member')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'db_table': 'business_family',
                'ordering': ['family_name'],
            },
        ),
        migrations.CreateModel(
            name='EventWorkGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('group_type', models.CharField(choices=[('kitchen', 'Cocina'), ('reception', 'Recepción'), ('parking', 'Estacionamiento'), ('cleaning', 'Limpieza'), ('security', 'Seguridad'), ('sound', 'Sonido'), ('worship', 'Alabanza'), ('children', 'Niños'), ('youth', 'Jóvenes'), ('ushers', 'Ujieres'), ('prayer', 'Oración'), ('setup', 'Montaje'), ('teardown', 'Desmontaje'), ('other', 'Otro')], default='other', max_length=50)),
                ('required_workers', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_groups', to='business.event')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_work_groups', to='business.member')),
            ],
            options={
                'verbose_name': 'Event Work Group',
                'verbose_name_plural': 'Event Work Groups',
                'db_table': 'business_eventworkgroup',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventIncome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('donation', 'Donación'), ('offering', 'Ofrenda'), ('ticket_sales', 'Venta de Boletos'), ('sponsorship', 'Patrocinio'), ('fundraising', 'Recaudación'), ('other', 'Otro')], default='donation', max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='business.eventbudget')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_donations', to='business.member')),
            ],
            options={
                'verbose_name': 'Event Income',
                'verbose_name_plural': 'Event Incomes',
                'db_table': 'business_eventincome',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('venue', 'Lugar/Renta'), ('food', 'Alimentos'), ('equipment', 'Equipo'), ('materials', 'Materiales'), ('transportation', 'Transporte'), ('marketing', 'Marketing'), ('staff', 'Personal'), ('decoration', 'Decoración'), ('sound', 'Sonido/Audio'), ('other', 'Otro')], default='other', max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('reimbursed', 'Reembolsado')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='business.eventbudget')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_expenses_paid', to='business.member')),
            ],
            options={
                'verbose_name': 'Event Expense',
                'verbose_name_plural': 'Event Expenses',
                'db_table': 'business_eventexpense',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='business.member'),
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_ministries', to='business.member')),
            ],
            options={
                'verbose_name': 'Ministry',
                'verbose_name_plural': 'Ministries',
                'db_table': 'business_ministry',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('father', 'Padre'), ('mother', 'Madre'), ('child', 'Hijo/a'), ('spouse', 'Cónyuge'), ('sibling', 'Hermano/a'), ('grandparent', 'Abuelo/a'), ('grandchild', 'Nieto/a'), ('uncle_aunt', 'Tío/a'), ('nephew_niece', 'Sobrino/a'), ('cousin', 'Primo/a'), ('other', 'Otro')], max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='business.family')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships', to='business.member')),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'db_table': 'business_familymember',
                'ordering': ['family', 'relationship_type'],
                'unique_together': {('family', 'member', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='EventWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Invitado'), ('confirmed', 'Confirmado'), ('declined', 'Rechazado'), ('completed', 'Completado')], default='invited', max_length=20)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='business.eventworkgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='business.member')),
            ],
            options={
                'verbose_name': 'Event Worker',
                'verbose_name_plural': 'Event Workers',
                'db_table': 'business_eventworker',
                'ordering': ['assigned_at'],
                'unique_together': {('work_group', 'member')},
            },
        ),
        migrations.CreateModel(
            name='MemberMinistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('leader', 'Líder'), ('co_leader', 'Co-Líder'), ('member', 'Miembro'), ('volunteer', 'Voluntario')], default='member', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_memberships', to='business.member')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_ministries', to='business.ministry')),
            ],
            options={
                'verbose_name': 'Member Ministry',
                'verbose_name_plural': 'Member Ministries',
                'db_table': 'business_memberministry',
                'ordering': ['-start_date'],
                'unique_together': {('member', 'ministry', 'start_date')},
            },
        ),
    ]
