# Generated by Django 6.0.4 on 2026-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='baptism_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de bautismo'),
        ),
        migrations.AddField(
            model_name='member',
            name='baptism_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lugar de bautismo'),
        ),
        migrations.AddField(
            model_name='member',
            name='baptized_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bautizado por'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_baptized',
            field=models.BooleanField(default=False, verbose_name='Bautizado'),
        ),
    ]
