# Generated by Django 6.0.4 on 2026-04-18 01:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_member_baptism_date_member_baptism_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLodging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Hospedaje habilitado')),
                ('total_needed', models.PositiveIntegerField(default=0, help_text='Cuántas personas necesitan hospedaje para este evento', verbose_name='Total de personas a hospedar')),
                ('notes', models.TextField(blank=True, verbose_name='Notas generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lodging', to='business.event')),
            ],
            options={
                'verbose_name': 'Hospedaje de Evento',
                'verbose_name_plural': 'Hospedajes de Evento',
                'db_table': 'business_event_lodging',
            },
        ),
        migrations.CreateModel(
            name='LodgingHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host_name', models.CharField(blank=True, help_text='Si no es miembro registrado, escribe el nombre aquí', max_length=200, verbose_name='Nombre del anfitrión')),
                ('address', models.TextField(verbose_name='Dirección / Ubicación')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad (personas)')),
                ('assigned_count', models.PositiveIntegerField(default=0, verbose_name='Personas asignadas')),
                ('active', models.BooleanField(default=True, verbose_name='Disponible')),
                ('notes', models.TextField(blank=True, help_text='Ej: tiene 2 hamacas, requieren llevar colchas, hay 1 cama matrimonial, etc.', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lodging_offers', to='business.member', verbose_name='Anfitrión')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='business.eventlodging')),
            ],
            options={
                'verbose_name': 'Anfitrión',
                'verbose_name_plural': 'Anfitriones',
                'db_table': 'business_lodging_host',
                'ordering': ['host_name', 'host__last_name'],
            },
        ),
        migrations.CreateModel(
            name='LodgingGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('representative_name', models.CharField(blank=True, help_text='Si no es miembro registrado', max_length=200, verbose_name='Nombre del representante')),
                ('adults', models.PositiveIntegerField(default=1, verbose_name='Adultos')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Niños')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lodging_as_guest', to='business.member', verbose_name='Representante del grupo')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='business.lodginghost')),
            ],
            options={
                'verbose_name': 'Grupo Huésped',
                'verbose_name_plural': 'Grupos Huéspedes',
                'db_table': 'business_lodging_guest',
                'ordering': ['created_at'],
            },
        ),
    ]
