# Generated by Django 6.0.4 on 2026-04-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_eventlodging_lodginghost_lodgingguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_lodging',
            field=models.BooleanField(default=False, verbose_name='Requiere hospedaje'),
        ),
    ]
