# Generated by Django 6.0.4 on 2026-04-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_event_requires_lodging'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodginghost',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='lodginghost',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, verbose_name='Longitud'),
        ),
    ]
