# Generated by Django 6.0.4 on 2026-05-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_lodginghost_latitude_lodginghost_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_service_eligible',
            field=models.BooleanField(default=False, verbose_name='Elegible para cultos'),
        ),
    ]
