# Generated by Django 6.0.4 on 2026-05-20 02:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0005_lodginghost_latitude_lodginghost_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase de FontAwesome, ej: fa-microphone', max_length=50, verbose_name='Ícono')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Inventario',
                'verbose_name_plural': 'Categorías de Inventario',
                'db_table': 'inventory_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('code', models.CharField(blank=True, help_text='Número de serie o código interno', max_length=50, verbose_name='Código / Serie')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('good', 'Bueno'), ('fair', 'Regular'), ('poor', 'Malo'), ('damaged', 'Dañado'), ('retired', 'Dado de baja')], default='good', max_length=20, verbose_name='Condición')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En uso'), ('lent', 'Prestado'), ('maintenance', 'En mantenimiento'), ('lost', 'Extraviado'), ('retired', 'Dado de baja')], default='available', max_length=20, verbose_name='Estado')),
                ('location', models.CharField(blank=True, help_text='Dónde se guarda normalmente', max_length=200, verbose_name='Ubicación')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de compra')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inventory/', verbose_name='Foto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='business.member', verbose_name='Responsable actual')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.itemcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'inventory_item',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('checkout', 'Préstamo / Salida'), ('return', 'Devolución'), ('maintenance', 'Enviado a mantenimiento'), ('maintenance_done', 'Regresó de mantenimiento'), ('transfer', 'Transferencia'), ('lost', 'Reportado extraviado'), ('found', 'Recuperado'), ('retired', 'Dado de baja')], max_length=20, verbose_name='Tipo de movimiento')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='Fecha esperada de devolución')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.item', verbose_name='Artículo')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_movements', to='business.member', verbose_name='Miembro involucrado')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'inventory_movement',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='inventory_i_status_25f563_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='inventory_i_categor_dcc1fb_idx'),
        ),
    ]
